# Generated by Django 4.2.30 on 2026-05-07 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mail.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.thread'),
        ),
        migrations.AddField(
            model_name='mailboxentry',
            name='custom_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='mail.folder'),
        ),
        migrations.AddField(
            model_name='mailboxentry',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='entries', to='mail.label'),
        ),
        migrations.AddField(
            model_name='mailboxentry',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_entries', to='mail.message'),
        ),
        migrations.AddField(
            model_name='mailboxentry',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_entries', to='mail.thread'),
        ),
        migrations.AddField(
            model_name='mailboxentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.message'),
        ),
        migrations.AlterUniqueTogether(
            name='mailboxentry',
            unique_together={('user', 'message')},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('user', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'slug')},
        ),
    ]
